# Generated by Django 6.0.1 on 2026-02-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'employee_table',
            },
        ),
    ]
