# Generated by Django 6.0.1 on 2026-02-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
            options={
                'db_table': 'instagram',
            },
        ),
    ]
