# Generated by Django 6.0.1 on 2026-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
                ('carmodel', models.CharField(max_length=100)),
                ('carprice', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
