# Generated by Django 6.0.1 on 2026-02-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('building_no', models.CharField(max_length=10)),
                ('established_year', models.IntegerField()),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='hod_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('office_room', models.CharField(max_length=20)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
            options={
                'db_table': 'hod_details',
            },
        ),
    ]
