# Generated by Django 6.0.1 on 2026-02-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comment'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
