# Generated by Django 6.0.1 on 2026-02-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_comment_options_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'actor'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'author'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'book'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'car'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'category'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'department'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'doctor'},
        ),
        migrations.AlterModelOptions(
            name='hod_details',
            options={'verbose_name_plural': 'hod_details'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'hospital'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'movie'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'post'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'service'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'student'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name_plural': 'studentprofile'},
        ),
    ]
