# Generated by Django 6.0.1 on 2026-02-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_alter_car_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('negotiating', 'Negotiating'), ('closed', 'Closed/Sold')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_inquiries', to='test1.user')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.car')),
            ],
            options={
                'verbose_name_plural': 'Inquiry',
                'db_table': 'inquiry_table',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='test1.inquiry')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'db_table': 'message_table',
                'ordering': ['sent_at'],
            },
        ),
    ]
