# Generated by Django 6.0.1 on 2026-02-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_inquiry_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='test1.car')),
            ],
            options={
                'verbose_name_plural': 'Car Images',
                'db_table': 'car_image_table',
            },
        ),
    ]
