# Generated by Django 6.0.1 on 2026-02-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_alter_message_options_testdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='test1.car')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.user')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'review_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
